function [matTable] = readData(indir)
    % Defining material properties
    rho   = [2810 8500 8500]; 
    cp    = [960 380 500]; 
    k     = [130 115 16.2];
    names = ["Aluminum" "Brass" "Steel"];  
    A     = pi * 0.0127^2; % m^2 --> cross-sectional area
    x     = linspace(0.034925,0.123825,8); % Position of thermocouples
    xAxis = [0, x];

    a   = dir([indir '*mA']);
    len = length(a);

    matTable(len) = struct( ...
        'name',        '',  ...
        'volts',       0,   ...
        'amps',        0,   ...
        'rho',         0,   ...
        'cp',          0,   ...
        'k',           0,   ...
        'alpha',       0,   ...
        't',           [],  ...
        'thermo_temp', [],  ...
        'init_vals',   [],  ...
        'ssValues',    [],  ...
        'y_fit',       [],  ...
        'delta',       0,   ...
        'H_exp',       0,   ...
        'T_0',         0,   ...
        'Q',           0,   ...
        'H_an',        0,   ...
        'x',           [],  ...
        'y',           []   ...
    );
    

    for i = 1 : len
        data = removeNaNs( readmatrix([indir a(i).name]) );
        b    = strsplit(a(i).name, '_'); % {'material','voltsV','ampsmA'}

        matTable(i).t           = data(:, 1);
        matTable(i).thermo_temp = data(:, 2 : end);

        matTable(i).name      = b{1};
        name_idx              = (names == matTable(i).name);
        matTable(i).volts     = str2double( extractBefore(b{2}, 'V') );
        matTable(i).amps      = str2double( extractBefore(b{3}, 'mA') ) / 1000;
        matTable(i).rho       = rho(name_idx);
        matTable(i).cp        = cp(name_idx); 
        matTable(i).k         = k(name_idx); 
        matTable(i).alpha     = matTable(i).k / ( matTable(i).rho * matTable(i).cp );
        matTable(i).init_vals = matTable(i).thermo_temp(1, 1 : end);
        matTable(i).ssValues  = matTable(i).thermo_temp(end, 1 : end);

        [p, S] = polyfit(x, matTable(i).ssValues, 1);
        [matTable(i).y_fit, matTable(i).delta] = polyval(p, xAxis, S);

        matTable(i).H_exp     = p(1);
        matTable(i).T_0       = matTable(i).y_fit(1);
        matTable(i).Q         = matTable(i).volts * matTable(i).amps;
        matTable(i).H_an      = matTable(i).Q / (matTable(i).k * A);
        matTable(i).x         = xAxis;
        matTable(i).y         = matTable(i).T_0 + matTable(i).H_an .* xAxis;
    end
end
